my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls
from article.views import article_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls',namespace='article')),
    path(r'mdeditor/', include('mdeditor.urls')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('index/notifications/',include(notifications.urls , namespace='notifications')),
    path('notice/',include('notice.urls',namespace='notice')),
    path('accounts/', include('allauth.urls')),
    path('',article_list,name='home'),


]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views
app_name = 'userprofile'

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('delete/<int:id>/',views.user_delete,name='delete'),
    path('edit/<int:id>/',views.profile_edit,name='edit'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='profile')
    phone = models.CharField(max_length=20,blank=True)
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/',blank=True)
    bio = models.TextField(max_length=500,blank=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save,sender=User)
def save_user_profile(sender,instance,**kwargs):
    instance.profile.save()













# Create your models here.

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()



class UserRegisterForm(forms.ModelForm):
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username' , 'email')

    def clean_password2(self):
        # def claen_ 这样的django自动调用哦
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError('密码输入不一致，请重试！')

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=('phone','avatar','bio')

userprofile/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import  authenticate,login,logout
from django.http import HttpResponse
from .forms import UserLoginForm,UserRegisterForm
from  django.contrib.auth.models import User
from  django.contrib.auth.decorators import login_required
from.forms import ProfileForm
from .models import Profile


# Create your views here.
def user_login(request):
    if request.method=='POST':
        user_login_form=UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            data=user_login_form.cleaned_data
            user =authenticate(username=data['username'],password=data['password'])
            if user:
                login(request,user)
                return redirect('article:article_list')
            else:
                return HttpResponse('账号或密码输入有误。请重新输入-')
        else:
            return HttpResponse('账号或密码输入不合法')
    elif request.method=='GET':
        user_login_form =UserLoginForm()
        context={'form':user_login_form}
        return render(request,'userprofile/login.html',context)
    else:
        return HttpResponse('请使用GET或者POST请求数据')
def user_logout(request):
    logout(request)
    return redirect('article:article_list')

def user_register(request):
    if request.method == "POST":
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            login(request,new_user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect("article:article_list")
        else :
            return HttpResponse('注册表单输入有误，请重新输入—')
    elif request.method=='GET':
        user_register_form = UserRegisterForm()
        context = {'form':user_register_form}
        return render(request,'userprofile/register.html',context)
    else:
        return HttpResponse('请使用GET或POST请求数据')

@login_required(login_url='/userprofile/login/')
# 必须登录 如果没有登陆则返回登录窗口去.
def user_delete(request,id):
    if request.method == "POST":
        user = User.objects.get(id=id)
        if request.user == user:
            logout(request)
            user.delete()
            return redirect('article:article_list')
        else:
            return HttpResponse('你没有删除操作的权限.')
    else:
        return HttpResponse('仅接受POST请求!')


@login_required(login_url='/userprofile/login/')
def profile_edit(request, id):
    user = User.objects.get(id=id)
    profile = Profile.objects.get(user_id=id)

    if request.method == 'POST':
        if request.user != user:
            return HttpResponse('你没有权限更改此用户！')
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            profile_cd = profile_form.cleaned_data
            profile.phone = profile_cd['phone']
            profile.bio = profile_cd['bio']
            if 'avatar' in request.FILES:
                profile.avatar=profile_cd['avatar']
            profile.save()
            return redirect('userprofile:edit',id=id)
        else:
            return HttpResponse('注册表单有误。请重新输入-')
    elif request.method=='GET':
        profile_form = ProfileForm()
        context = {'profile_form':profile_form,'profile':profile,'user':user}
        return render(request,'userprofile/edit.html',context)
    else:
        return HttpResponse('请使用POST或者GET请求数据')

templates/userprofile/edit.html
{% extends "base.html" %} {% load static %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
{% comment %} <script type="text/javascript" color="0,0,0" opacity='0.7' zIndex="-2" count="200" src="https://files.cnblogs.com/files/lfri/canvas-nest.js"></script> {% endcomment %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">用户名: {{ user.username }}</div>
            <br>
             {% if profile.avatar %}
                <div class="col-md-4">头像</div>
                <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
            {% else %}
                <h5 class="col-md-4">暂无头像</h5>
            {% endif %}
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                 <!-- avatar -->
                 <div class="form-group col-md-4">
                    <label for="avatar">上传头像</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <!-- phone -->
                <div class="form-group col-md-4">
                    <label for="phone">电话</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>
                <!-- bio -->
                <div class="form-group col-md-4">
                    <label for="bio">简介</label>
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
<script src="//itggg.cn/cdn/bubbly-bg.js"></script>
<script>bubbly({
    colorStart: "#111",
    colorStop: "#422",
    bubbleFunc: () => `hsla(0, 100%, 50%, ${Math.random() * 0.25})`
});</script>
{% endblock content %}

templates/userprofile/login.html
{% extends "base.html" %} {% load static %}
{% block title %} 登录 {% endblock title %}
{% block style %} #msg{width: 50%;line-height: 40px;font-size: 14px;text-align: center;} {% endblock style %}
{% block content %}
<div class="jq22-container" style="padding-top:100px">
    <div class="login-wrap">
        <div class="login-html">
            <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">登录</label>
			<input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab"><a href='{% url "userprofile:register" %}'>注册</a></label>
			<div class="login-form">
                <form method="post" action=".">
                
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <!-- 密码 -->
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <!--滑块验证-->
                <div class="group">
							<div class="container">
							    <div id="captcha" style="position: relative" data-type="password"></div>
								<div id="msg"></div>
							</div>
						</div>
                
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
                <div class="hr"></div>
						<div class="foot-lnk">
							<a href='{% url "password_reset_recover" %}'>忘记密码？</a>
				</div>
                
            </form>
                <br>
            </div>
        </div>
    </div>
</div>
 {% block script %}<script src="js/jigsaw.js"></script>
 <script>
jigsaw.init(document.getElementById('captcha'), function () {
  	 flag=true;
    document.getElementById('msg').innerHTML = '登录成功！'  
  })
</script> 
 {% endblock script %}
{% comment %} <script src="js/jigsaw.js"></script> {% endcomment %}
{% comment %} {% block script %}
{% endblock script %}
<script>
jigsaw.init(document.getElementById('captcha'), function () {
  	 flag=true;
    document.getElementById('msg').innerHTML = '登录成功！'  
  })
</script>  {% endcomment %}
{% endblock content %}

templates/userprofile/register.html
{% extends "base.html" %} {% load static %}
{% block title %} 注册 {% endblock title %}
{% block style %} #msg{width: 50%;line-height: 40px;font-size: 14px;text-align: center;} {% endblock style %}
{% block content %}
<div class="jq22-container" style="padding-top:100px">>
    <div class="login-wrap">
        <div class="login-html">
        <input id="tab-2" type="radio" name="tab" class="sign-in" ><label for="tab-2" class="tab"><a href='{% url "userprofile:login" %}'>登录</a></label>
			<input id="tab-1" type="radio" name="tab" class="sign-up" checked><label for="tab-1" class="tab">注册</label>
            <br>

            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-13">
                    <label for="username">昵称</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <!-- 邮箱 -->
                <div class="form-group col-md-13">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-13">
                    <label for="password">设置密码</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <!-- 确认密码 -->
                <div class="form-group col-md-13">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}