article/urls.py
from django.urls import path
from . import views

app_name='article'

urlpatterns=[
    path('article_list/',views.article_list,name='article_list'),
    path('article_detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article-create/',views.article_create,name='article_create'),
    path('article-safe-delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    path('article-update/<int:id>/',views.article_update,name='article_update'),
    path(
        'increase-likes/<int:id>/',
        views.IncreaseLikesView.as_view(),
        name='increase_likes'
    ),


]

my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls
from article.views import article_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls',namespace='article')),
    path(r'mdeditor/', include('mdeditor.urls')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('index/notifications/',include(notifications.urls , namespace='notifications')),
    path('notice/',include('notice.urls',namespace='notice')),
    path('accounts/', include('allauth.urls')),
    path('',article_list,name='home'),


]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views
app_name = 'userprofile'

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('delete/<int:id>/',views.user_delete,name='delete'),
    path('edit/<int:id>/',views.profile_edit,name='edit'),
]

templates/back_to_top_func.html
<!-- Author: 鹦鹉 -->
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
<!DOCTYPE html>
{% load static %}
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css"  href="{% static 'md_css/pygments.css' %}" >
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css"
>
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
	<link rel="stylesheet" href="{% static 'css/dmaku.css' %}">
	<style>{% block style %}{% endblock %}</style>


</head>

<body>
<script>
/* 鼠标点击文字特效 */
 var f_idx = 0;
 var c_idx = 0;
 jQuery(document).ready(function($) {
  $("body").click(function(e) {
   var font = new Array("干饭人,干饭魂,干饭都是人上人!", "是个狼人", "有钱的捧个钱场，没钱的回家拿钱捧个钱场。", " 吾生也有涯，而吃也无涯。", " 如果生活踹了你好多脚，别忘了给它两个耳光，反抗总比流泪强。", " 专家建议，每天睡眠不要超过24小时，有个差不多就行了，也别太过。", "人的一生，本就是一个认人、识人的过程。有的人起始于相逢，终止于相处；有的人曾经入了眼，如今离了心。" ,"愿我们都不会把所有別人对我们的好，视为理所当然。因为知足，会更接近幸福。", "世界那么大，你总会遇见一个对的人，让你放下所有的防备和不安，静静的依偎在他的身边。", "林花谢了春红,太匆匆,无奈朝来寒雨晚来风。胭脂泪,留人醉,几时重,自是人生长恨水长东。", "花红易衰似郎意,水流无限似侬愁。", "独上江楼思渺然,月光如水水如天。");
 var color = new Array('#ff0000','#eb4310','#f6941d','#fbb417','#ffff00','#cdd541','#99cc33','#3f9337','#219167','#239676','#24998d','#1f9baa','#0080ff','#3366cc','#333399','#003366','#800080','#a1488e','#c71585','#bd2158');
   var $i = $("<span />").text(font[f_idx]);
   f_idx = (f_idx + 1) % font.length;
 c_idx = (c_idx + 1) % color.length;
   var x = e.pageX,
    y = e.pageY;
   $i.css({
    "z-index": 99999999999999999999999999999999999999999999999999999999999999999999999999 ,
    "top": y - 20,
    "left": x,
    "position": "absolute",
    "font-weight": "bold",
    "color": color[c_idx]
   });
   $("body").append($i);
   $i.animate({
     "top": y - 180,
     "opacity": 0
    },
    1500,
    function() {
     $i.remove();
    });
  });
 });
</script>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <div id="wrapper">
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>

    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <!--
        popper.js 采用 cdn 远程引入，意思是你不需要把它下载到本地。
        在实际的开发中推荐静态文件尽量都使用 cdn 的形式。
        教程采用本地引入是为了让读者了解静态文件本地部署的流程。
    -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js'%}"></script>
    {% comment %} <script src="{% static 'js/dmaku.js'%}"></script>
    <script src="{% static 'js/styles.js'%}"></script> {% endcomment %}
    <script src="{% static 'js/jigsaw.js'%}"></script>

       {% block script %}{% endblock script %}
    {% include 'back_to_top_func.html' %}
<style>
    html, body {
        height: 100%;
        margin: 0;
    }

    #wrapper {
        min-height: 100%;
        margin-bottom: -40px;
    }

    #footer,
    #push {
        height: 60px;
    }
</style>

<script src="//itggg.cn/cdn/bubbly-bg.js"></script>
<script>bubbly({
    colorStart: "#fff4e6",
    colorStop: "#ffe9e4",
    blur: 1,
    compose: "source-over",
    bubbleFunc: () => `hsla(${Math.random() * 50}, 100%, 50%, .3)`
});</script>


<script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css"/>
<script src="https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget/autoload.js"></script>
 
<script src="https://eqcn.ajz.miesnfu.com/wp-content/plugins/wp-3d-pony/live2dw/lib/L2Dwidget.min.js"></script>

  <script>
    //默认使用的萌娘
    L2Dwidget.init({ "model": { jsonPath:
          "https://unpkg.com/live2d-widget-model-shizuku@1.0.5/assets/shizuku.model.json",
	       "scale": 1 }, "display": { "position": "right", "width": 220, "height":300 ,
	       "hOffset": 0, "vOffset": -20 }, "mobile": { "show": true, "scale": 0.5 },
	       "react": { "opacityDefault": 0.8, "opacityOnHover": 0.1 } });
  </script>

</body>

</html>

templates/footer.html
{% load static %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white">thanks for your view!</p>
    </div>
</footer>

templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="#">我的笔记</a>

    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
        <!-- 条目 -->

        <li class="nav-item">

          <a class="nav-link" href="{% url 'article:article_list' %}">笔记</a>
        </li>
        {% if user.is_authenticated %}
        <!-- 如果用户已经登录，则显示用户名下拉框 -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if unread_count %}
            <svg viewBox="0 0 8 8"
                 width="8px"
                 height="8px">
                <circle cx="4"
                        cy="4"
                        r="4"
                        fill="#ff6b6b"
                        ></circle>
            </svg>
        {% endif %}
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'notice:list' %}">通知
            {% if unread_count %}
            <span class="badge badge-danger">{{ unread_count }}</span>
            {% endif %}
                </a>
                <a class="dropdown-item" href="{% url 'article:article_create' %}">写文章</a>
                <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
                <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
              <a class="dropdown-item" href="{%url 'userprofile:logout' %}">退出登录</a>
            </div>
        </li>
    <!-- 如果用户未登录，则显示 “登录” -->
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
        </li>
    <!-- if 语句在这里结束 -->
    {% endif %}

          {% if user.is_authenticated %}
<form
    style="display:none;"
    id="user_delete"
    action="{% url 'userprofile:delete' user.id %}"
    method="POST"
>
{% csrf_token %}
    <button type="submit">发送</button>
</form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function(index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>


{% endif %}


      </ul>
    </div>

  </div>
</nav>