article/urls.py
from django.urls import path
from . import views

app_name='article'

urlpatterns=[
    path('article_list/',views.article_list,name='article_list'),
    path('article_detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article-create/',views.article_create,name='article_create'),
    path('article-safe-delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    path('article-update/<int:id>/',views.article_update,name='article_update'),
    path(
        'increase-likes/<int:id>/',
        views.IncreaseLikesView.as_view(),
        name='increase_likes'
    ),


]

comment/urls.py
from  django.urls import path
from . import views

app_name = 'comment'

urlpatterns=[
    path('post-comment/<int:article_id>',views.post_comment,name='post_comment'),
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls
from article.views import article_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls',namespace='article')),
    path(r'mdeditor/', include('mdeditor.urls')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('index/notifications/',include(notifications.urls , namespace='notifications')),
    path('notice/',include('notice.urls',namespace='notice')),
    path('accounts/', include('allauth.urls')),
    path('',article_list,name='home'),


]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views
app_name = 'userprofile'

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('delete/<int:id>/',views.user_delete,name='delete'),
    path('edit/<int:id>/',views.profile_edit,name='edit'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import  timezone
from mdeditor.fields import MDTextField
from django.urls import reverse
from taggit.managers import TaggableManager
from PIL import Image
#from imagekit.models import ProcessedImageField
#from imagekit.processors import ResizeToFit




class ArticleColumn(models.Model):
    title = models.CharField(max_length=100,blank = True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title



class ArticlePost(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    column = models.ForeignKey(
        ArticleColumn,
            null=True,
        blank = True,
        on_delete=models.CASCADE,
        related_name ='acticle'
    )
    likes = models.PositiveIntegerField(default=0)
    title = models.CharField(max_length=100)
    body = MDTextField()
    avatar = models.ImageField(upload_to = 'article/%Y%m%d/',blank = True)
    created = models.DateTimeField(default=timezone.now)
    update=models.DateTimeField(auto_now=True)
    total_views = models.PositiveIntegerField(default=0)
    tags = TaggableManager(blank=True)
    '''avatar = ProcessedImageField(
        upload_to='article/%Y%m%d',
        processors=[ResizeToFit(width=400)],
        format='JPEG',
        options={'quality': 100},
    )'''

    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('article:article_detail',args=[self.id])
    def save(self,*args,**kwargs):
        article = super().save(*args,**kwargs)
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x,y)=image.size
            new_x=400
            new_y=int(new_x*(y/x))
            resized_image = image.resize((new_x,new_y),Image.ANTIALIAS)
            resized_image.save(self.avatar.path)
        return article



# Create your models here.

article/forms.py
from django import  forms
from .models import ArticlePost
from mdeditor.fields import MDTextField

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title','body','tags','avatar')
        

article/views.py
from django.shortcuts import render,redirect
from django.http import  HttpResponse
from .models import ArticlePost,ArticleColumn
from .forms import ArticlePostForm
from django.contrib.auth.models import User
import markdown
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import  Q
from comment.models import Comment
from comment.forms import  CommentForm
from django.views import View


class IncreaseLikesView(View):
    def post(self, request, *args, **kwargs):
        article = ArticlePost.objects.get(id=kwargs.get('id'))
        article.likes += 1
        article.save()
        return HttpResponse('success')

def article_list(request):

    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')
    print(search,order,column,tag)
    article_list = ArticlePost.objects.all()
    if search:
        article_list = ArticlePost.objects.filter(Q(title__icontains=search)|Q(body__icontains=search))
    else:
        search=''
    if column is not None and column.isdigit():
        print('完成了')
        article_list = article_list.filter(column=column)

    if tag and tag !='None':
        article_list = article_list.filter(tags__name__in=[tag])

    if order == 'total_views':
        article_list = article_list.order_by('-total_views')
    paginator = Paginator(article_list,3)
    page=request.GET.get('page')
    #print(page)
    articles=paginator.get_page(page)

    context={'articles':articles,'order': order,'search':search,'column':column,'tag':tag}
    return render(request,'article/list.html',context)


def article_detail(request,id):
    article = ArticlePost.objects.get(id=id)
    article.total_views+=1
    article.save(update_fields=['total_views'])
    comments = Comment.objects.filter(article=id)
    comment_form = CommentForm()
    md=markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    article.body=md.convert(article.body.replace("\n", '  \n'))
    for comment in comments:
        comment.body = md.convert(comment.body.replace("\n", '  \n'))
    context={'article':article,'toc':md.toc,'comments':comments,'comment_form':comment_form,}
    return render(request,'article/detail.html',context)

@login_required(login_url='/userprofile/login/')
def article_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        print('完成')
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(request.POST,request.FILES)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中


            new_article = article_post_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            new_article.author = User.objects.get(id=request.user.id)
            # 将新文章保存到数据库中
            if request.POST['column']!='none':
                new_article.column =  ArticleColumn.objects.get(id=request.POST['column'])

            new_article.save()
            article_post_form.save_m2m()
            # 完成后返回到文章列表
            return redirect("article:article_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        # 赋值上下文
        context = { 'article_post_form': article_post_form,'columns':columns }
        # 返回模板
        return render(request, 'article/create.html', context)

@login_required(login_url='/userprofile/login/')
def article_safe_delete(request,id):
    if request.method == "POST":
        print('完成')
        article=ArticlePost.objects.get(id=id)
        if request.user != article.author:
            return HttpResponse('对不起，您无权删除这篇文章!')
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse('仅允许post请求')


@login_required(login_url='/userprofile/login/')
def article_update(request,id):
    article = ArticlePost.objects.get(id=id)
    if request.user!=article.author:
        return HttpResponse('对不起，您无权修改这篇文章!')
    if request.method=='POST':
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title=request.POST['title']
            article.body=request.POST['body']
            if request.POST['column'] !='none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column=None
            article.save()
            return redirect('article:article_detail',id=id)
        else :
            return HttpResponse('表单内容有误，请重新填写.')
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context={'article':article , 'article_post_form':article_post_form,'columns':columns,}
        return render(request,'article/update.html',context)





# Create your views here.

templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action="." enctype="multipart/form-data">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题图 -->
                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>

                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group">
        <label for="column">栏目</label>
        <select class="form-control"
                id="column"
                name="column"
        >
                <option value="none">请选择栏目..</option>
            {% for column in columns %}
                <option value="{{ column.id }}">{{ column }}</option>
            {% endfor %}
        </select>
    </div>
                <!-- 文章标签 -->
    <div class="form-group">
        <label for="tags">标签</label>
        <input type="text"
               class="form-control col-3"
               id="tags"
               name="tags"
        >
    </div>

                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <div>
                        {{article_post_form.media}}
                        {{article_post_form.body}}
                    </div>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    笔记详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-9">
        <!-- 标题及作者 -->
        <h1 class="mt-4 mb-4">{{ article.title }}</h1>
        <div class=" alert alert-success"><div>

            作者：{{ article.author }}
            {% if user == article.author %}
         · <a href="#" onclick="confirm_safe_delete()">删除笔记</a>
        <form
            style="display: none;"
            id="safe_delete"
            action="{% url 'article:article_safe_delete' article.id%}"
            method="POST"
            >
            {% csrf_token %}
            <button type="submit">发送</button>
        </form>
        · <a href="{%url 'article:article_update' article.id %}">
            编辑笔记
        </a>
            {% endif %}
            </div>
            <div>
                浏览:{{article.total_views}}
            </div>
        </div>

            <!-- 文章正文 -->
        <div class="col-12">
            <p>{{ article.body|safe }}</p>
        </div>
            <div style="text-align:center;" class="mt-4">
    <button class="btn btn-outline-danger"
            type="button"
            onclick="validate_is_like(
                     '{% url 'article:increase_likes' article.id %}',
                     {{ article.id }},
                     {{ article.likes }}
                     )"
            >
        <span>觉得有用</span>
        <span>
            <i class="fas fa-heart"></i>
        </span>
        <span id="likes_number">
            {{ article.likes }}
        </span>
    </button>
</div>
               <!-- 显示评论 -->
{% load mptt_tags %}
<h4>共有{{ comments.count }}条追加补充</h4>
<div class="row">
    <!-- 遍历树形结构 -->
    {% recursetree comments %}
        <!-- 给 node 取个别名 comment -->
        {% with comment=node %}
            <div class="{% if comment.reply_to %}
                        offset-1 col-11
                        {% else %}
                        col-12
                        {% endif %}"
                 id="comment_elem_{{ comment.id }}"
            >
                <hr>
                <p>
                    <strong style="color: pink">
                        {{ comment.user }}
                    </strong>

                    {% if comment.reply_to %}
                        <i class="far fa-arrow-alt-circle-right"
                           style="color: cornflowerblue;"
                        ></i>
                        <strong style="color: pink">
                            {{ comment.reply_to }}
                        </strong>
                    {% endif %}

                </p>
                <div>{{ comment.body|safe }}</div>

                <div>
                    <span style="color: gray">
                        {{ comment.created|date:"Y-m-d H:i" }}
                    </span>

                    <!-- modal 按钮 -->
                    <button type="button"
                            class="btn btn-light btn-sm text-muted"
                            onclick="load_modal({{ article.id }}, {{ comment.id }})"
                    >
                        回复
                    </button>
                </div>

                <!-- Modal -->
                <div class="modal fade"
                     id="comment_{{ comment.id }}"
                     tabindex="-1"
                     role="dialog"
                     aria-labelledby="CommentModalCenter"
                     aria-hidden="true"
                >
                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                        <div class="modal-content" style="height: 480px">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                            </div>
                            <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                        </div>

                    </div>
                </div>

                {% if not comment.is_leaf_node %}
                    <div class="children">
                        {{ children }}
                    </div>
                {% endif %}
            </div>


        {% endwith %}
    {% endrecursetree %}
</div>
            <hr>
    {% if user.is_authenticated %}
        <div>
            <form
                action="{% url 'comment:post_comment' article.id %}"
                method="POST"
            >
            {% csrf_token %}
                <div class="form-group">
                    <label for="body">
                        <strong>
                            做一下补充：
                        </strong>
                    </label>
                  <div>
                      {{comment_form.media}}
                      {{comment_form.body}}
                  </div>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary ">发送</button>
            </form>
        </div>
        <br>
    {% else %}
        <br>
        <h5 class="row justify-content-center">
            请<a href="{% url 'userprofile:login' %}">登录</a>后回复
        </h5>
        <br>
    {% endif %}








        <!-- 发表评论 -->

</div>

        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
        <h4><strong>目录</strong></h4>
        <hr>
        <div>
            {{ toc|safe }}
        </div>
    </div>
        </div>


    </div>
</div>
<!-- 粘性侧边栏样式 -->
<style>
    .sidebar{
        will-change: min-height;
    }

    .sidebar__inner{
        transform: translate(0, 0); /* For browsers don't support translate3d. */
        transform: translate3d(0, 0, 0);
        will-change: position, transform;
    }
</style>
<script>
    function confirm_safe_delete()
    {
        layer.open(
            {
                title:'确认删除',
                content:'确认删除这个笔记吗?',
                yes: function (index,layero){
                    $('form#safe_delete button').click();
                    layer.close(index);
                },
            }
        )
    }
</script>

{% endblock content %}
{% block script %}
<!-- 引入粘性侧边栏 -->
<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
</script>
<!-- Ckeditor自适应 -->
<script>
    $(".django-ckeditor-widget").removeAttr('style');
</script>
<script>
    // 加载 modal
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        // 加载编辑器
        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="/comment/post-comment/' +
                article_id +
                '/' +
                comment_id +
                '"' +
                ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                comment_id +
                '"></iframe>';
            $(modal_body).append(content);
        };

        $(modal_id).modal('show');
    }
    function post_reply_and_show_it(new_comment_id) {
        let next_url = "{% url 'article:article_detail' article.id %}";
        // 去除 url 尾部 '/' 符号
        next_url = next_url.charAt(next_url.length - 1) == '/' ? next_url.slice(0, -1) : next_url;
        // 刷新并定位到锚点
        window.location.replace(next_url + "#comment_elem_" + new_comment_id);
    };
</script>

<script src="{% static 'csrf.js' %}"></script>
<script>
    // 点赞功能主函数
    function validate_is_like(url, id, likes) {
        // 取出 LocalStorage 中的数据
        let storage = window.localStorage;
        const storage_str_data = storage.getItem("my_blog_data");
        let storage_json_data = JSON.parse(storage_str_data);
        // 若数据不存在，则创建空字典
        if (!storage_json_data) {
            storage_json_data = {}
        };
        // 检查当前文章是否已点赞。是则 status = true
        const status = check_status(storage_json_data, id);
        if (status) {
            layer.msg('已经点过赞了哟~');
            // 点过赞则立即退出函数
            return;
        } else {
            // 用 Jquery 找到点赞数量，并 +1
            $('span#likes_number').text(likes + 1).css('color', '#dc3545');
        }
        // 用 ajax 向后端发送 post 请求
        $.post(
            url,
            // post 只是为了做 csrf 校验，因此数据为空
            {},
            function(result) {
                if (result === 'success') {
                    // 尝试修改点赞数据
                    try {
                        storage_json_data[id] = true;
                    } catch (e) {
                        window.localStorage.clear();
                    };
                    // 将字典转换为字符串，以便存储到 LocalStorage
                    const d = JSON.stringify(storage_json_data);
                    // 尝试存储点赞数据到 LocalStorage
                    try {
                        storage.setItem("my_blog_data", d);
                    } catch (e) {
                        // code 22 错误表示 LocalStorage 空间满了
                        if (e.code === 22) {
                            window.localStorage.clear();
                            storage.setItem("my_blog_data", d);
                        }
                    };
                } else {
                    layer.msg("与服务器通信失败..过一会儿再试试呗~");
                }

            }
        );
    };

    // 辅助点赞主函数，验证点赞状态
    function check_status(data, id) {
        // 尝试查询点赞状态
        try {
            if (id in data && data[id]) {
                return true;
            } else {
                return false;
            }
        } catch (e) {
            window.localStorage.clear();
            return false;
        };
    };
</script>
{% endblock script %}

templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}


<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <!-- 面包屑导航 -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?search={{ search }}&column={{ column }}&tag={{ tag }}">
                    最近写入
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}&column={{ column }}&tag={{ tag }}">
                    最多观看
                </a>
            </li>
        </ol>
    </nav>

    <!-- 搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text"
                    class="form-control mb-2 mr-sm-2"
                    name="search"
                    placeholder="搜索文章..."
                    required
                >
            </form>
        </div>
    </div>

    <!-- 搜索提示语 -->
    {% if search %}
        {% if articles %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
            <hr>
        {% endif %}
    {% endif %}

    <!-- 列表循环 -->
    <div class="row mt-2">
        {% for article in articles %}
            <!-- 文章内容 -->

            <!-- 标题图 -->
            {% if article.avatar %}
                <div class="col-3">
                    <img src="{{ article.avatar.url }}"
                         alt="avatar"
                         style="max-width:100%; border-radius: 20px"
                    >
                </div>
            {% endif %}

            <div class="col">
                <!-- 栏目 -->
                {% if article.column %}
                    <a  role="button"
                        href="{% url 'article:article_list' %}?column={{ article.column.id }}"
                        class="btn btn-sm mb-2
                            {% if article.column.title == 'python' %}
                                btn-success
                            {% elif article.column.title == '数学' %}
                                btn-danger
                            {% elif article.column.title == 'English' %}
                                btn-warning
                            {% endif %}
                        "
                    >
                        {{ article.column }}
                    </a>
                {% endif %}

                <!-- 标签 -->
                <span>
                    {% for tag in article.tags.all %}
                        <a href="{% url 'article:article_list' %}?tag={{ tag }}"
                           class="badge badge-secondary"
                        >
                            {{ tag }}
                        </a>
                    {% endfor %}
                </span>

                <!-- 标题 -->
                <h4>
                    <b>
                        <a href="{% url 'article:article_detail' article.id %}"
                           style="color: black;"
                        >
                            {{ article.title }}
                        </a>
                    </b>
                </h4>
                <!-- 摘要 -->
                <div>
                    <p style="color: gray;">
                        {{ article.body|slice:'100' }}...
                    </p>
                </div>
                <!-- 注脚 -->
                <p>
                    <!-- 附加信息 -->
                    <span>
                        <i class="fas fa-eye" style="color: lightskyblue;"></i>
                        {{ article.total_views }}&nbsp;&nbsp;&nbsp;
                    </span>
                    <span>
                        <i class="fas fa-comments" style="color: yellowgreen;"></i>
                        {{ article.comments.count }}&nbsp;&nbsp;&nbsp;
                    </span>
                    <span>
                        <i class="fas fa-clock" style="color: pink;"></i>

                        {{ article.created|date:'Y-m-d' }}

                    </span>
                </p>
            </div>
            <hr style="width: 100%;"/>
        {% endfor %}
    </div>

    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                       class="btn btn-secondary"
                    >
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                       class="btn btn-secondary"
                    >
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                       class="btn btn-success"
                    >
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>

</div>

{% endblock content %}

templates/article/update.html
{% extends "base.html" %} {% load static %}
{% block title %} 更新笔记 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">笔记标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <!-- 文章栏目 -->
    <div class="form-group">
        <label for="column">栏目</label>
        <select class="form-control"
                id="column"
                name="column"
        >
                <option value="none">请选择栏目..</option>
            {% for column in columns %}
                <option value="{{ column.id }}"
                    {% if column.id == article.column.id %}
                        selected
                    {% endif %}
                >
                    {{ column }}
                </option>
            {% endfor %}
        </select>
    </div>
                <div class="form-group">
                    <label for="body">笔记正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}